name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: app/release
        
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        # Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE
        path: app/release
        
    - name: Display structure of downloaded files
      run: ls -R app/release
      
